// Route-strategy selection, kept out of the RoutePlanner component.
//
// Every field read here (arrival_risk_score, expected_spoilage_loss,
// transport_cost_total, expected_realised_value, ...) is computed
// destination-by-destination on the backend (destination_service.py),
// using that destination's own transit time fed into the trained spoilage
// model as a real feature -- not re-derived here from a daily forecast
// bucket (that was the previous, incorrect approach: multiple destinations
// with different transit times collapsed onto the same "days_from_now"
// bucket and showed identical risk). This file only picks
// min/max across the real per-destination numbers the API already returned.

// Four real strategies, each the actual argmin/argmax of the candidate
// list on its own metric -- never independently fabricated routes.
export function pickRouteStrategies(destinations) {
  if (!destinations || destinations.length === 0) return null;
  const fastest = [...destinations].sort((a, b) => a.travel_time_hours - b.travel_time_hours)[0];
  const lowestCost = [...destinations].sort((a, b) => a.transport_cost_total - b.transport_cost_total)[0];
  const lowestRisk = [...destinations].sort((a, b) => a.arrival_risk_score - b.arrival_risk_score)[0];
  const bestValue = [...destinations].sort((a, b) => b.expected_realised_value - a.expected_realised_value)[0];
  return { fastest, lowestCost, lowestRisk, bestValue };
}

// 3-4 short, real reasons for the recommended (best-value) destination,
// generated by comparing it against the other real candidates -- never
// generic AI text. Returns {key, params} pairs (i18next keys under
// market.reason*, see locales/*/common.json) rather than formatted English
// strings, so every language renders the same real comparison.
export function buildWhyReasons(top, destinations) {
  if (!destinations || destinations.length <= 1) {
    return [{ key: "market.onlyOption", params: {} }];
  }

  const reasons = [];
  const others = destinations.filter((d) => d.destination_id !== top.destination_id);
  const closest = [...destinations].sort((a, b) => a.distance_km - b.distance_km)[0];
  const priciest = [...destinations].sort((a, b) => b.expected_price - a.expected_price)[0];
  const highestValue = [...destinations].sort((a, b) => b.expected_realised_value - a.expected_realised_value)[0];

  if (highestValue.destination_id === top.destination_id) {
    reasons.push({ key: "market.reasonHighestValue", params: { count: destinations.length } });
  }

  if (top.destination_id === priciest.destination_id) {
    reasons.push({ key: "market.reasonStrongPrice", params: { price: top.expected_price } });
  } else {
    const higherPriced = others.find((d) => d.expected_price > top.expected_price);
    if (higherPriced) reasons.push({ key: "market.reasonCheaperOverridesPrice", params: { market: higherPriced.name } });
  }

  if (top.destination_id === closest.destination_id) {
    reasons.push({ key: "market.reasonClosest", params: {} });
  } else {
    const extraKm = Math.round((top.distance_km - closest.distance_km) * 10) / 10;
    reasons.push({ key: "market.reasonFartherButBetter", params: { extraKm } });
  }

  const higherRiskAlt = others.find((d) => d.arrival_risk_score > top.arrival_risk_score);
  if (higherRiskAlt) {
    reasons.push({ key: "market.reasonLowerRisk", params: { market: higherRiskAlt.name } });
  } else if (top.type === "storage_facility") {
    reasons.push({ key: "market.reasonColdStorage", params: {} });
  }

  return reasons.slice(0, 4);
}
